### ISSUE TITLE
Nuget package?

### ISSUE THREAD

**Issue by victortrusov** [sergezhigunov/OpenGost#14]
Thank you very much for such a useful library!
Do you have plans to add it to the nuget.org? Couldn't find it there.

**Comment by sergezhigunov** [comment]
Yes, I plan to release the package with the end of the milestone [0.1.0](https://github.com/sergezhigunov/OpenGost/milestone/1) until November 30, 2020.

**Comment by sergezhigunov** [comment]
Due to lack of free time, postponed to December 12, 2020. Sry.
